version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-kastro
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: kastro_exam_db
    ports:
      - "3306:3306"
    volumes:
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - kastro-net

  backend:
    build:
      context: .             # Root context, where Dockerfile is
    container_name: kastro-backend
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: kastro_exam_db
      DB_USER: root
      DB_PASSWORD: rootpass
    networks:
      - kastro-net

networks:
  kastro-net:
